title = "조은우 기술 블로그"
baseURL = "https://jonnung.dev/"
languageCode = "ko-kr"
defaultContentLanguage = "ko"
hasCJKLanguage = true
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"]

paginate = 18

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

[services]
  [services.googleAnalytics]
    ID = "UA-43871004-5"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[Languages.ko]
  title = "조은우 기술 블로그"
  languageName = "한국어"
  languageCode = "ko-kr"
  contentDir = "content"
  weight = 1

  [Languages.ko.menu]
  [[Languages.ko.menu.main]]
    pageRef = "/"
    name = "Home"
    url = "/"
    weight = 10
  [[Languages.ko.menu.main]]
    pageRef = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 20

[Languages.ko.params]
  sitename = "조은우 기술 블로그"
  defaultColor = "auto"
  description = "학습하고 경험한 기술에 대해 이야기 합니다."
  mainSections = ["posts"]
  toc = true
  tocOpen = false
  goToTop = true
  dateFormat = "2006-01-02"
  rssFeedDescription = "summary"

[Languages.ko.params.author]
  name = "JONNUNG"
  intro = "조은우 기술 블로그"
  description = "학습하고 경험한 기술에 대해 이야기 합니다."

[Languages.ko.params.webmanifest]
  theme_color = "#434648"

[[Languages.ko.params.socialIcons]]
  name = "github"
  url = "https://github.com/jonnung"
[[Languages.ko.params.socialIcons]]
  name = "email"
  url = "mailto:jonnung@gmail.com"
[[Languages.ko.params.socialIcons]]
  name = "rss"
  url = "/index.xml"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.87.0"
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"
